apiVersion: apps/v1
kind: Deployment
metadata:
  name: testa
  labels:
    app: testa

spec:
  replicas: 2
  selector:
    matchLabels:
      app: testa
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

    #progressDeadlineSeconds: 600

  template:
    metadata:
      labels:
        app: testa
    spec:
      containers:
        - image: sammybloom/flask-app:latest
          imagePullPolicy: Always
          name: testa
          ports:
            - containerPort: 80
