apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone

spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

    #progressDeadlineSeconds: 600

  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: sammybloom/flask-app:latest
          imagePullPolicy: Always
          name: capstone
          ports:
            - containerPort: 80
