version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  # kubernetes: circleci/kubernetes@0.4.0
  kubernetes: circleci/kubernetes@1.0.2

commands:
  destroy-cluster:
    description: Destroy EKS Cluster.
    parameters:
        cluster-name:
          description: |
            Name of the EKS cluster
          type: string

    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name eksctl-capstone-cloud-devops --region us-west-2
            aws cloudformation delete-stack --stack-name eksctl-<< parameters.cluster-name >>-cluster --region us-west-2
parameters:
  docker_image:
    type: string
    default: python:3.10.0-base 
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7-stretch

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            # sudo python3 -m venv ./.devops
            # source ./.devops/Scripts/activate
            sudo python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt --user
            # Install hadolint
            sudo make install-hadolint

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lints!
      - run:
          name: run lint
          command: |
            # source ./.devops/Scripts/activate
            . venv/bin/activate
            make lint

  build-and-push-image:
    machine: true
    steps:
         - checkout
         - run: |
            docker build -t sammybloom/flask-app:latest .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-blessme12
            docker push sammybloom/flask-app:latest
  # Creation of Cluster
  create-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
        default: capstone
    steps:
      - run:
          name: Install the eksctl tool
          command: |
            if which eksctl > /dev/null; then
              echo "eksctl is already installed"
              exit 0
            fi
            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
              | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
              SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download
      - aws-eks/install-aws-iam-authenticator:
          release-tag: ''
      - aws-eks/create-cluster:
          cluster-name: capstone
          node-type: t3.medium
     

   # Test the Cluster
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name: 
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
            kubectl get pods
            kubectl describe pods
            kubectl get nodes
            kubectl get deployment
            kubectl get services -o wide
          name: Test cluster
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployments/nginx-deployment.yaml
          resource-name: deployments/capstone
      - kubernetes/create-or-update-resource:
          resource-file-path: deployments/app-service.yaml        
     
workflows:
  default:
    jobs:          
      - build
      - create-cluster:
          requires:
            - build
      - test-cluster:
          cluster-name: capstone
          requires:
            - create-cluster
      - create-deployment:
          cluster-name: capstone
          requires:
            - test-cluster